version: '3'

services:
  haproxy:
    image: haproxy:2.2-alpine
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/app/haproxy/haproxy.cfg:ro
      - ./haproxy/blacklist_agent.lst:/usr/local/etc/app/haproxy/blacklist_agent.lst:ro
      - ./haproxy/whitelist_agent.lst:/usr/local/etc/app/haproxy/whitelist_agent.lst:ro
    ports:
      - 9090:80
    depends_on:
      - backend1
      - backend2

  backend1:
    build: ./backend1
    volumes:
      - ./backend1:/usr/local/etc/app

  backend2:
    build: ./backend2
    volumes:
      - ./backend2:/usr/local/etc/app